1722075883.353564 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:98 __init__ INFO: Starting DataFlowKernel with config
Config(
    app_cache=True, 
    checkpoint_files=None, 
    checkpoint_mode=None, 
    checkpoint_period=None, 
    dependency_resolver=None, 
    executors=(ThreadPoolExecutor(
        label='threads', 
        max_threads=2, 
        storage_access=None, 
        thread_name_prefix='', 
        working_dir=None
    ),), 
    exit_mode='cleanup', 
    garbage_collect=True, 
    initialize_logging=True, 
    internal_tasks_max_threads=10, 
    max_idletime=120.0, 
    monitoring=None, 
    retries=0, 
    retry_handler=None, 
    run_dir='runinfo', 
    std_autopath=None, 
    strategy='simple', 
    strategy_period=5, 
    usage_tracking=0
)
1722075883.353771 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:100 __init__ INFO: Parsl version: 2024.07.22
1722075883.353878 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.usage_tracking.usage:118 __init__ DEBUG: Tracking level: 0
1722075883.353969 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:128 __init__ INFO: Run id is: 24ad4db0-75db-40ef-9b11-9ba1ed5470be
1722075883.421279 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:135 __init__ DEBUG: Considering candidate for workflow name: /home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py
1722075883.421412 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:135 __init__ DEBUG: Considering candidate for workflow name: /home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py
1722075883.421464 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:135 __init__ DEBUG: Considering candidate for workflow name: /home/ubuntu/data/test/parsl_pro/parsl_script.py
1722075883.421512 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:141 __init__ DEBUG: Using parsl_script.py as workflow name
1722075883.421673 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.memoization:163 __init__ INFO: App caching initialized
1722075883.421742 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.jobs.strategy:145 __init__ DEBUG: Scaling strategy: simple
1722075883.424812 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1016 submit DEBUG: Task 0 will be sent to executor threads
1722075883.424917 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:818 _add_output_deps DEBUG: Adding output dependencies
1722075883.424972 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1067 submit DEBUG: Added output dependencies
1722075883.425019 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1080 submit DEBUG: Gathering dependencies
1722075883.425065 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1083 submit DEBUG: Gathered dependencies
1722075883.425108 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1098 submit INFO: Task 0 submitted for App install_cunumeric, not waiting on any dependency
1722075883.425169 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1104 submit DEBUG: Task 0 set to pending state with AppFuture: <AppFuture at 0x7fcefead1280 state=pending>
1722075883.425586 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.dataflow.memoization:222 check_memo DEBUG: Task 0 will not be memoized
1722075883.425823 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1016 submit DEBUG: Task 1 will be sent to executor threads
1722075883.426123 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:818 _add_output_deps DEBUG: Adding output dependencies
1722075883.427745 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1067 submit DEBUG: Added output dependencies
1722075883.427821 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1080 submit DEBUG: Gathering dependencies
1722075883.427930 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1083 submit DEBUG: Gathered dependencies
1722075883.428035 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.dataflow.dflow:776 launch_task INFO: Parsl task 0 try 0 launched on executor threads
1722075883.428118 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1098 submit INFO: Task 1 submitted for App preprocess_data, not waiting on any dependency
1722075883.428300 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.dataflow.dflow:1476 log_std_stream INFO: Standard out for task 0 will not be redirected.
1722075883.428410 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1104 submit DEBUG: Task 1 set to pending state with AppFuture: <AppFuture at 0x7fcefe8904c0 state=pending>
1722075883.428548 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.dataflow.dflow:1476 log_std_stream INFO: Standard error for task 0 will not be redirected.
1722075883.429002 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _launch_if_ready_async on thread Dependency-Launch_0
1722075883.429338 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.dataflow.memoization:222 check_memo DEBUG: Task 1 will not be memoized
1722075883.430476 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.dataflow.dflow:776 launch_task INFO: Parsl task 1 try 0 launched on executor threads
1722075883.430647 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard out for task 1 will be redirected to preprocess_data.out
1722075883.430735 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard error for task 1 will be redirected to preprocess_data.err
1722075883.430844 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _launch_if_ready_async on thread Dependency-Launch_0
1722075883.432859 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1016 submit DEBUG: Task 2 will be sent to executor _parsl_internal
1722075883.434083 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:818 _add_output_deps DEBUG: Adding output dependencies
1722075883.434147 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1067 submit DEBUG: Added output dependencies
1722075883.434199 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1080 submit DEBUG: Gathering dependencies
1722075883.434318 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1083 submit DEBUG: Gathered dependencies
1722075883.434374 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1098 submit INFO: Task 2 submitted for App deferred_getattr, waiting on task 1
1722075883.434436 2024-07-27 18:24:43 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1104 submit DEBUG: Task 2 set to pending state with AppFuture: <AppFuture at 0x7fcefe8901f0 state=pending>
1722075883.434638 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.dataflow.dflow:664 _launch_if_ready_async DEBUG: Task 2 has outstanding dependencies, so launch_if_ready skipping
1722075883.434958 2024-07-27 18:24:43 MainProcess-1068524 Dependency-Launch_0-140527001065216 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _launch_if_ready_async on thread Dependency-Launch_0
1722075883.437396 2024-07-27 18:24:43 MainProcess-1068524 ThreadPoolExecutor-0_1-140526984279808 parsl.app.errors:113 reraise DEBUG: Reraising exception of type <class 'parsl.app.errors.BashExitFailure'>
1722075883.437787 2024-07-27 18:24:43 MainProcess-1068524 ThreadPoolExecutor-0_1-140526984279808 parsl.dataflow.dflow:351 handle_exec_update INFO: Task 1 try 0 failed with exception of type BashExitFailure
1722075883.437934 2024-07-27 18:24:43 MainProcess-1068524 ThreadPoolExecutor-0_1-140526984279808 parsl.dataflow.dflow:397 handle_exec_update ERROR: Task 1 failed after 0 retry attempts
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 348, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 618, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 117, in reraise
    raise v
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/bash.py", line 94, in remote_side_bash_executor
    raise pe.BashExitFailure(func_name, proc.returncode)
parsl.app.errors.BashExitFailure: bash_app preprocess_data failed with unix exit code 127
1722075883.438703 2024-07-27 18:24:43 MainProcess-1068524 ThreadPoolExecutor-0_1-140526984279808 concurrent.futures:332 _invoke_callbacks ERROR: exception calling callback for <AppFuture at 0x7fcefe8904c0 state=finished raised BashExitFailure>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 348, in handle_exec_update
    res = self._unwrap_remote_exception_wrapper(future)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 618, in _unwrap_remote_exception_wrapper
    result.reraise()
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 117, in reraise
    raise v
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/errors.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/app/bash.py", line 94, in remote_side_bash_executor
    raise pe.BashExitFailure(func_name, proc.returncode)
parsl.app.errors.BashExitFailure: bash_app preprocess_data failed with unix exit code 127

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/concurrent/futures/_base.py", line 330, in _invoke_callbacks
    callback(self)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 1123, in callback_adapter
    self.launch_if_ready(task_record)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/site-packages/parsl/dataflow/dflow.py", line 646, in launch_if_ready
    self.dependency_launch_pool.submit(self._launch_if_ready_async, task_record)
  File "/home/ubuntu/miniconda3/envs/parsl/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
1722075883.439751 2024-07-27 18:24:43 MainProcess-1068524 ThreadPoolExecutor-0_1-140526984279808 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard out for task 1 will be redirected to preprocess_data.out
1722075883.439867 2024-07-27 18:24:43 MainProcess-1068524 ThreadPoolExecutor-0_1-140526984279808 parsl.dataflow.dflow:1478 log_std_stream INFO: Standard error for task 1 will be redirected to preprocess_data.err
1722075888.422408 2024-07-27 18:24:48 MainProcess-1068524 JobStatusPoller-Timer-Thread-140527011726768-140527009457920 parsl.jobs.strategy:184 _general_strategy DEBUG: general strategy starting with strategy_type simple for 0 executors
1722075888.422669 2024-07-27 18:24:48 MainProcess-1068524 JobStatusPoller-Timer-Thread-140527011726768-140527009457920 parsl.process_loggers:27 wrapped DEBUG: Normal ending for _general_strategy on thread JobStatusPoller-Timer-Thread-140527011726768
1722075889.758144 2024-07-27 18:24:49 MainProcess-1068524 MainThread-140527072118592 parsl.dataflow.dflow:1206 atexit_cleanup WARNING: Python is exiting with a DFK still running. You should call parsl.dfk().cleanup() before exiting to release any resources
